sudo: required
language: python
services:
  - docker

before_script:
  - ./build_travis_settings.sh
  - ./docker-compose.sh up redis-appdata-test
#  - ./docker-compose.sh run --rm manage-test migrate --database=default
#  - ./docker-compose.sh run --rm manage-test migrate --database=sierra

script: sleep 30 && ls -al docker_data/redis-appdata-test/ && ls -al docker_data/redis-appdata-test/logs/ && cat docker_data/redis-appdata-test/logs/log.txt
