sudo: required
language: python
services:
  - docker

before_script:
  - ./build_travis_settings.sh
  - ./docker-compose.sh pull default-db-test sierra-db-test solr-test redis-appdata-test
  - ./docker-compose.sh build manage-test test
  - ./init-dockerdata.sh test
  
script: ./docker-compose.sh run --rm test
