sudo: required
language: python
services:
  - docker

before_script:
  - ./build_travis_settings.sh
  - ./docker-compose.sh run --rm manage-test migrate --database=default
  - ./docker-compose.sh run --rm manage-test migrate --database=sierra

script: ./docker-compose.sh run --rm test
